version: '3'
services:
  mysql:
    container_name: shop_mysql
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: prestashop
    networks:
      - prestashop_network
  prestashop:
    volumes:
      - "/storage/docker/reverseproxy/caddy/data:/data"
      - "/storage/docker/reverseproxy/caddy/www:/www"
      - "/storage/docker/shop:/"
    container_name: prestashop
    image: prestashop/prestashop:latest
    restart: unless-stopped
    environment:
      DB_SERVER: shop_mysql
      DB_NAME: prestashop
      DB_USER: root
      DB_PASSWD: admin
      PS_INSTALL_AUTO: 1
      PS_DOMAIN: shop.taire.de:8080
      PS_FOLDER_ADMIN: admintso1337
      PS_FOLDER_INSTALL: admintso1337
      ADMIN_MAIL: shop@taire.de
    networks:
      - prestashop_network
      - reverseproxy
networks:
    prestashop_network:
    reverseproxy:
                external: true