version: '3'
services:
  mysql:
    image: docker.io/mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: CLKJerjdOIJFdkIIJ
      MYSQL_DATABASE: prestashop
    networks:
      - prestashop_network
  prestashop:
    volumes:
      - "/storage/docker/shop/admintso1337:/admintso1337"
    image: prestashop/prestashop:latest
    environment:
      DB_SERVER: mysql
      DB_NAME: prestashop
      DB_USER: mysql
      DB_PASSWD: CLKJerjdOIJFdkIIJ
      PS_INSTALL_AUTO: 1
      PS_DOMAIN: shop.taire.de:8080
      PS_FOLDER_ADMIN: admintso1337
      PS_FOLDER_INSTALL: admintso1337
      PS_ENABLE_SSL: 1
      ADMIN_MAIL: shop@taire.de
    networks:
      - prestashop_network
      - reverseproxy
networks:
    prestashop_network:
    reverseproxy:
      external: true