version: '3'
services:
  mariadb:
    image: docker.io/mariadb:latest
    environment:
      MARIADB_ROOT_PASSWORD: CLKJerjdOIJFdkIIJ
      MARIADB_USER: prestashop
      MARIADB_PASSWORD: CLKJerjdOIJFdkIIJ
      MARIADB_DATABASE: prestashop
    networks:
      - prestashop_network
  prestashop:
    volumes:
      - "/storage/docker/shop/admintso1337:/admintso1337"
    image: prestashop/prestashop:latest
    environment:
      DB_SERVER: mariadb
      DB_NAME: prestashop
      DB_USER: prestashop
      DB_PASSWD: CLKJerjdOIJFdkIIJ
      PS_INSTALL_AUTO: 1
      PS_DOMAIN: shop.taire.de
      PS_FOLDER_ADMIN: admintso1337
      PS_FOLDER_INSTALL: admintso1337
      PS_ENABLE_SSL: 1
      ADMIN_MAIL: shop@taire.de
    networks:
      - prestashop_network
      - reverseproxy
networks:
    prestashop_network:
    reverseproxy:
      external: true