version: "3.8"
services:

        caddy:
                image: "docker.io/caddy:latest"
                deploy:
                        replicas: 1
                configs:
                        - source: "Caddyfile_2023-07-19-2"
                          target: "/etc/caddy/Caddyfile"
                volumes:
                        - "/storage/docker/reverseproxy/caddy/data:/data"
                        - "/storage/docker/reverseproxy/caddy/www:/www"
                ports:
                        - "80:80"
                        - "443:443"
                networks:
                        - "reverseproxy"
configs:
        Caddyfile_2023-07-19-2:
                file: ./Caddyfile

networks:
        reverseproxy:
                external: true