version: '3'

services: 
    wordpress:
        image: wordpress
        volumes: 
            - /storage/docker/blog/wordpress/:/var/www/html
        ports: 
            - "8000:80"
        depends_on: 
            - wordpress-mysql
        networks: 
            - mariadb
            - reverseproxy
        environment: 
            WORDPRESS_DB_HOST: wordpress-mysql
            WORDPRESS_DB_USER: wordpress
            WORDPRESS_DB_PASSWORD: wordpress
            WORDPRESS_DB_NAME: wordpress-mysql

    wordpress-mysql:
        image: mariadb
        volumes: 
            - /storage/docker/blog/wordpress-mysql/var/lib/mysql:/var/lib/mysql
            - /storage/docker/blog/wordpress-mysql/:docker-entrypoint-initdb.d
        environment:
            MYSQL_RANDOM_ROOT_PASSWORD: "1"
            MYSQL_DATABASE: wordpress
            MYSQL_USER: wordpress
        networks: 
            - mariadb

networks: 
    mariadb:
    reverseproxy:
        external: true