homeserver:
  address: http://synapse:8008
  domain: taire.de
appservice:
  address: http://mautrix-whatsapp:29318
  hostname: 0.0.0.0
  port: 29318
  database:
    type: sqlite3
    uri: mautrix-whatsapp.db
    max_open_conns: 20
    max_idle_conns: 2
  provisioning:
    prefix: /_matrix/provision/v1
    shared_secret: disable
  id: whatsapp
  bot:
    username: whatsappbot
    displayname: WhatsApp bridge bot
    avatar: mxc://maunium.net/NeXNQarUbrlYBiPCpprYsRqr
  as_token: {{ secret "mautrix-whatsapp_as-token-2020-09-30" }}
  hs_token: {{ secret "mautrix-whatsapp_hs-token-2020-09-30" }}
bridge:
  username_template: {{ "whatsapp_{{.}}" }}
  displayname_template: {{ '{{if .Notify}}{{.Notify}}{{else}}{{.Jid}}{{end}} 👁️‍🗨️ ' }}
  community_template: {{ "whatsapp_{{.Localpart}}={{.Server}}" }}
  connection_timeout: 20
  login_qr_regen_count: 2
  max_connection_attempts: 3
  connection_retry_delay: -1
  report_connection_retry: true
  chat_list_wait: 30
  portal_sync_wait: 600
  call_notices:
    start: true
    end: true
  initial_chat_sync_count: 10
  initial_history_fill_count: 20
  recovery_chat_sync_count: -1
  recovery_history_backfill: true
  sync_max_chat_age: 259200
  sync_with_custom_puppets: true
  login_shared_secret: ""
  invite_own_puppet_for_backfilling: true
  private_chat_portal_meta: false
  allow_user_invite: false
  command_prefix: '!wa'
  permissions:
    '@vol:taire.de': admin
  relaybot:
    enabled: false
    management: ""
    invites: []
    message_formats:
      m.audio: {{ "<b>{{ .Sender.Displayname }}</b> sent an audio file" }}
      m.emote: {{ "'* <b>{{ .Sender.Displayname }}</b> {{ .Message }}'" }}
      m.file: {{ "<b>{{ .Sender.Displayname }}</b> sent a file" }}
      m.image: {{ "<b>{{ .Sender.Displayname }}</b> sent an image" }}
      m.location: {{ "<b>{{ .Sender.Displayname }}</b> sent a location" }}
      m.notice: {{ "'<b>{{ .Sender.Displayname }}</b>: {{ .Message }}'" }}
      m.text: {{ "'<b>{{ .Sender.Displayname }}</b>: {{ .Message }}'" }}
      m.video: {{ "<b>{{ .Sender.Displayname }}</b> sent a video" }}
logging:
  directory: ./logs
  file_name_format: {{ "'{{.Date}}-{{.Index}}.log'" }}
  file_date_format: "2006-01-02"
  file_mode: 384
  timestamp_format: Jan _2, 2006 15:04:05
  print_level: debug